services:
  nginx: 
    image: nginx:alpine
    ports:
      - "80:80"
    volumes: 
      - ./nginx.comf:/etc/nginx/nginx.comf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped